# Generated by Django 4.2.9 on 2026-08-16 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0002_ideathonteam_ideathonconfig_ideathonmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="ideathonteam",
            name="avatar",
            field=models.CharField(
                choices=[
                    ("rocket", "🚀 Rocket"),
                    ("bulb", "💡 Bulb"),
                    ("fire", "🔥 Fire"),
                    ("star", "⭐ Star"),
                    ("brain", "🧠 Brain"),
                    ("lightning", "⚡ Lightning"),
                    ("diamond", "💎 Diamond"),
                    ("trophy", "🏆 Trophy"),
                    ("compass", "🧭 Compass"),
                    ("atom", "⚛️ Atom"),
                ],
                default="rocket",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="IdeathonInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_ideathon_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideathon_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="polls.ideathonteam",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("team", "invitee")},
            },
        ),
    ]
