# Generated by Django 4.2.9 on 2026-09-06 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0003_ideathonteam_avatar_ideathoninvite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ideathonconfig",
            name="min_team_size",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.CreateModel(
            name="IdeathonInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideathon_interest",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
