# Generated by Django 4.2.9 on 2026-09-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackform",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schedulesession",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sessionbookmark",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
