# Generated by Django 4.2.9 on 2026-09-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "schedule",
            "0002_feedbackform_is_featured_schedulesession_is_featured_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulesession",
            name="day",
            field=models.IntegerField(default=1),
        ),
    ]
