# Generated by Django 4.2.9 on 2026-09-20 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_schedulesession_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulesubsession",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_sessions",
                to="schedule.schedulesession",
            ),
        ),
    ]
