# Generated by Django 4.2.9 on 2026-09-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0004_alter_schedulesubsession_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedbackform",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="sessionbookmark",
            name="is_featured",
        ),
        migrations.AddField(
            model_name="schedulesession",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="schedulesession",
            name="status",
            field=models.CharField(default="published", max_length=20),
        ),
    ]
