# Generated by Django 4.2.9 on 2026-09-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0005_remove_feedbackform_is_featured_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulesession",
            name="feedback_auto_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schedulesession",
            name="feedback_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="schedulesession",
            name="is_meal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schedulesession",
            name="is_parallel",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schedulesession",
            name="meal_category",
            field=models.CharField(blank=True, default="Lunch", max_length=50),
        ),
    ]
