# Generated by Django 4.2.9 on 2026-09-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0007_paperbookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperbookmark",
            name="reminder_minutes",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="sessionbookmark",
            name="reminder_minutes",
            field=models.IntegerField(default=5),
        ),
    ]
