# Generated by Django 4.2.9 on 2026-09-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0008_paperbookmark_reminder_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperbookmark",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schedulesession",
            name="notify_all_5_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedulesession",
            name="notify_featured_60_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sessionbookmark",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
