# Generated by Django 4.2.9 on 2026-08-10 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("speakers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to user account for chat/login",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="speaker_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
