# Generated by Django 4.2.9 on 2026-08-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="contact_person_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="contact_person_role",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=12, max_length=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=12, max_length=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="stall_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="stall_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="sponsors/stalls/"
            ),
        ),
    ]
