"""Test coverage matrix — what each layer tests."""

TEST_COVERAGE = {
    "Layer 1: API Load Testing": {
        "description": "HTTP endpoint throughput, latency, error rates",
        "coverage": [
            "Authentication (login, refresh, profile)",
            "Schedule browsing (heaviest read endpoint)",
            "Chat & connections",
            "Polls & voting",
            "Check-in operations",
            "Photo uploads",
            "Staff directory",
            "Notifications",
            "Leaderboard",
            "Sponsors & speakers",
        ],
        "tools": "Locust (Python)",
        "weight": 20,
    },
    "Layer 2: Database Stress": {
        "description": "PostgreSQL under concurrent connection & query load",
        "coverage": [
            "Connection pool exhaustion",
            "Transaction throughput (TPS)",
            "Query latency",
            "Concurrent write races",
            "Index efficiency",
            "Lock contention",
        ],
        "tools": "pgbench (PostgreSQL native)",
        "weight": 15,
    },
    "Layer 3: WebSocket Capacity": {
        "description": "Django Channels + Daphne under concurrent connections",
        "coverage": [
            "Concurrent WebSocket handshakes",
            "Signaling throughput",
            "Channel layer performance (Redis)",
            "Session persistence",
        ],
        "tools": "Custom websocket-client",
        "weight": 10,
    },
    "Layer 4: WebRTC Voice Calling": {
        "description": "Voice call signaling + coturn TURN/STUN health",
        "coverage": [
            "Concurrent call sessions",
            "SDP negotiation latency",
            "ICE candidate exchange",
            "coturn relay capacity",
            "Call state management",
        ],
        "tools": "Custom + turnutils_uclient",
        "weight": 10,
    },
    "Layer 5: Security Testing": {
        "description": "Authentication bypass, injection, XSS, JWT security",
        "coverage": [
            "SQL injection attempts",
            "XSS payload testing",
            "JWT tampering",
            "Auth bypass attempts",
            "Rate limiting verification",
            "CSRF protection",
            "Password brute force resistance",
        ],
        "tools": "Custom Python probes",
        "weight": 15,
    },
    "Layer 6: Endurance / Soak": {
        "description": "30-minute sustained load — memory leak detection",
        "coverage": [
            "Memory growth over time",
            "Response time drift",
            "Connection leak detection",
            "Cache growth patterns",
            "Log rotation",
        ],
        "tools": "Locust + psutil monitoring",
        "weight": 10,
    },
    "Layer 7: Chaos Engineering": {
        "description": "Failure injection — kill services mid-test",
        "coverage": [
            "Redis restart mid-test",
            "PostgreSQL connection kills",
            "Network partition simulation",
            "Recovery time measurement",
            "Data integrity after failure",
        ],
        "tools": "systemctl + custom scripts",
        "weight": 10,
    },
    "Layer 8: Data Integrity": {
        "description": "Race conditions on concurrent writes",
        "coverage": [
            "Concurrent poll voting (no double-vote)",
            "Simultaneous check-ins",
            "Race on connection requests",
            "Point award atomicity",
        ],
        "tools": "Custom concurrent request scripts",
        "weight": 5,
    },
    "Layer 9: Network Resilience": {
        "description": "Real-world network condition simulation",
        "coverage": [
            "Slow network (3G simulation)",
            "Packet loss handling",
            "High latency scenarios",
            "Connection drops",
        ],
        "tools": "tc (Linux traffic control)",
        "weight": 3,
    },
    "Layer 10: Real-World Scenario": {
        "description": "Complete user journey E2E under realistic load",
        "coverage": [
            "Full check-in rush simulation",
            "Keynote start — 200 users open schedule",
            "Lunch time — meal scan burst",
            "Post-session — poll voting spike",
            "Networking hour — chat + connections",
        ],
        "tools": "Locust orchestrated scenarios",
        "weight": 2,
    },
}
