# Generated by Django 4.2.9 on 2026-08-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0002_announcement"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Announcement",
        ),
    ]
