# Generated by Django 4.2.9 on 2026-08-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_participantimport_registration_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participantimport",
            name="registration_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
