# Generated by Django 4.2.9 on 2026-08-22 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_participantimport_registration_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("librarian", "Librarian & Head"),
                            ("deputy", "Deputy Librarian"),
                            ("assistant", "Assistant Librarian"),
                            ("staff", "Staff"),
                        ],
                        max_length=20,
                    ),
                ),
                ("designation", models.CharField(max_length=200)),
                ("department", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="staff/")),
                ("linkedin_url", models.URLField(blank=True)),
                ("profile_url", models.URLField(blank=True)),
                ("scholar_url", models.URLField(blank=True)),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Display sort order"),
                ),
                ("is_public", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="StaffPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("participants", "Participants"),
                            ("ideathon", "Ideathon Teams"),
                            ("meal_scanner", "Meal Scanner"),
                            ("checkin_scanner", "Check-In Scanner"),
                            ("schedule", "Events & Schedule"),
                            ("photos", "Photos"),
                            ("checkpoint", "Checkpoint"),
                            ("feed", "Posts & Feed"),
                            ("polls", "Polls"),
                            ("qa_manager", "Q&A Manager"),
                            ("leaderboard", "Leaderboard"),
                            ("chat", "Chat & Connections"),
                            ("reported_messages", "Reported Messages"),
                            ("shake_logs", "Shake Connect Logs"),
                            ("chat_analytics", "Chat Analytics"),
                            ("notifications", "Notifications"),
                            ("sponsors", "Sponsors"),
                            ("speakers", "Speakers"),
                            ("users_manage", "User Management"),
                            ("reports", "Reports"),
                            ("settings", "Settings"),
                        ],
                        max_length=50,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "module")},
            },
        ),
    ]
