# Generated by Django 4.2.9 on 2026-08-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_staffprofile_staffpermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="warning_acknowledged",
            field=models.BooleanField(
                default=False, help_text="Has the user acknowledged the warning"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="warning_acknowledged_at",
            field=models.DateTimeField(
                blank=True, help_text="When the warning was acknowledged", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="warning_response",
            field=models.TextField(
                blank=True, help_text="User message/response when acknowledging"
            ),
        ),
    ]
