# Generated by Django 4.2.9 on 2026-09-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_warning_acknowledged_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffpermission",
            name="module",
            field=models.CharField(
                choices=[
                    ("participants", "Participants"),
                    ("papers", "Papers & Posters"),
                    ("ideathon", "Ideathon Teams"),
                    ("meal_scanner", "Meal Scanner"),
                    ("checkin_scanner", "Check-In Scanner"),
                    ("schedule", "Events & Schedule"),
                    ("photos", "Photos"),
                    ("checkpoint", "Checkpoint"),
                    ("feed", "Posts & Feed"),
                    ("polls", "Polls"),
                    ("qa_manager", "Q&A Manager"),
                    ("leaderboard", "Leaderboard"),
                    ("chat", "Chat & Connections"),
                    ("reported_messages", "Reported Messages"),
                    ("shake_logs", "Shake Connect Logs"),
                    ("chat_analytics", "Chat Analytics"),
                    ("notifications", "Notifications"),
                    ("sponsors", "Sponsors"),
                    ("speakers", "Speakers"),
                    ("users_manage", "User Management"),
                    ("reports", "Reports"),
                    ("settings", "Settings"),
                ],
                max_length=50,
            ),
        ),
    ]
