# Generated by Django 4.2.9 on 2026-08-20 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("photos", "0001_photo_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="SelfiePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=12)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=12)),
                (
                    "radius_meters",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Allowed radius in meters for unlocking upload",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=10, help_text="Points awarded upon verified upload"
                    ),
                ),
                (
                    "sample_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="selfie_points/samples/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "selfie_points",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SelfieSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="selfie_submissions/%Y/%m/")),
                ("user_latitude", models.DecimalField(decimal_places=8, max_digits=12)),
                (
                    "user_longitude",
                    models.DecimalField(decimal_places=8, max_digits=12),
                ),
                (
                    "distance_meters",
                    models.FloatField(
                        help_text="Calculated distance in meters at time of upload"
                    ),
                ),
                ("verified_in_geofence", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "selfie_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="photos.selfiepoint",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selfie_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "selfie_submissions",
                "ordering": ["-created_at"],
                "unique_together": {("user", "selfie_point")},
            },
        ),
    ]
