# Generated by Django 4.2.9 on 2026-08-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0002_selfiepoint_selfiesubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="photosettings",
            name="selfie_upload_open",
            field=models.BooleanField(default=True),
        ),
    ]
