# Generated by Django 4.2.9 on 2026-08-21 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sponsors", "0002_sponsor_contact_person_name_and_more"),
        ("photos", "0003_photosettings_selfie_upload_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfiepoint",
            name="checkpoint_type",
            field=models.CharField(
                choices=[
                    ("selfie", "Selfie Checkpoint"),
                    ("sponsor_zone", "Sponsor Zone"),
                ],
                default="selfie",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="selfiepoint",
            name="corridor_width_meters",
            field=models.PositiveIntegerField(
                default=30, help_text="Width of the sponsor corridor in meters"
            ),
        ),
        migrations.AddField(
            model_name="selfiepoint",
            name="point_a_lat",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="selfiepoint",
            name="point_a_lng",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="selfiepoint",
            name="point_b_lat",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="selfiepoint",
            name="point_b_lng",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="selfiepoint",
            name="sponsors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Sponsors present in this zone (for sponsor_zone type only)",
                related_name="checkpoint_zones",
                to="sponsors.sponsor",
            ),
        ),
        migrations.AddField(
            model_name="selfiesubmission",
            name="points_awarded",
            field=models.PositiveIntegerField(
                default=0, help_text="Points actually credited to user"
            ),
        ),
        migrations.AddField(
            model_name="selfiesubmission",
            name="rejected_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="selfiesubmission",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="selfiesubmission",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="selfiesubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="selfiepoint",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="selfiepoint",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="selfiepoint",
            name="points",
            field=models.PositiveIntegerField(
                default=10, help_text="Points awarded upon admin approval"
            ),
        ),
        migrations.AlterField(
            model_name="selfiepoint",
            name="radius_meters",
            field=models.PositiveIntegerField(
                default=20, help_text="Allowed radius in meters"
            ),
        ),
        migrations.AlterField(
            model_name="selfiesubmission",
            name="distance_meters",
            field=models.FloatField(
                help_text="Calculated distance in meters at time of visit"
            ),
        ),
        migrations.AlterField(
            model_name="selfiesubmission",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="selfie_submissions/%Y/%m/"
            ),
        ),
    ]
