# Generated by Django 4.2.9 on 2026-08-30 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0002_sponsor_contact_person_name_and_more"),
        ("photos", "0004_selfiepoint_checkpoint_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selfiepoint",
            name="corridor_width_meters",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="selfiepoint",
            name="points",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="selfiepoint",
            name="radius_meters",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="selfiepoint",
            name="sponsors",
            field=models.ManyToManyField(
                blank=True, related_name="checkpoint_zones", to="sponsors.sponsor"
            ),
        ),
        migrations.AlterField(
            model_name="selfiesubmission",
            name="distance_meters",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="selfiesubmission",
            name="points_awarded",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="SelfiePointImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="selfie_points/samples/")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "selfie_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="photos.selfiepoint",
                    ),
                ),
            ],
            options={
                "db_table": "selfie_point_images",
                "ordering": ["order"],
            },
        ),
    ]
