# Generated by Django 4.2.9 on 2026-08-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkins", "0003_mealwindow_mealpass"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkin",
            name="checkin_type",
            field=models.CharField(default="conference", max_length=20),
        ),
        migrations.AlterField(
            model_name="mealpass",
            name="meal_type",
            field=models.CharField(
                choices=[("meal", "Meal"), ("lunch", "Lunch"), ("dinner", "Dinner")],
                default="meal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mealwindow",
            name="meal_type",
            field=models.CharField(
                choices=[("meal", "Meal"), ("lunch", "Lunch"), ("dinner", "Dinner")],
                default="meal",
                max_length=20,
            ),
        ),
    ]
