# Generated by Django 4.2.9 on 2026-08-30 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "checkins",
            "0004_alter_checkin_checkin_type_alter_mealpass_meal_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mealwindow",
            options={"ordering": ["-date", "start_time"]},
        ),
        migrations.AlterUniqueTogether(
            name="mealpass",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="mealpass",
            name="guest_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="mealpass",
            name="guest_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="mealpass",
            name="guest_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="mealpass",
            name="guest_reg_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="mealwindow",
            name="end_time",
            field=models.TimeField(blank=True, help_text="e.g. 14:00", null=True),
        ),
        migrations.AddField(
            model_name="mealwindow",
            name="notified_closing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mealwindow",
            name="notified_opening",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mealwindow",
            name="start_time",
            field=models.TimeField(blank=True, help_text="e.g. 12:00", null=True),
        ),
        migrations.AlterField(
            model_name="mealpass",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_passes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mealwindow",
            name="is_open",
            field=models.BooleanField(default=False),
        ),
    ]
