# Generated by Django 4.2.9 on 2026-08-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkins", "0005_mealwindow_times_mealpass_guest"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealwindow",
            name="notify_close_minutes_before",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="mealwindow",
            name="notify_open_minutes_before",
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name="mealwindow",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mealwindow",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
